### ISSUE TITLE
Unable to install extension due to missing icon

### ISSUE THREAD

**Issue by nionis** [ruipgil/pocketmark#1]

**Comment by ruipgil** [comment]
This is when you install from the chrome extension store?

**Comment by nionis** [comment]
Yeah, 
![untitled](https://cloud.githubusercontent.com/assets/1877679/19147706/afc1988c-8bb9-11e6-8a34-47c72e298648.png)

**Comment by ruipgil** [comment]
Fixed in version 0.3.7
